### ISSUE TITLE
activity indicator doesn't back to its position

### ISSUE THREAD

**Issue by ghost** [inspace-io/INSPullToRefresh#54] opened 2015-07-29 10:38 UTC
App starts up and trigger pull to refresh automatically immediately,  when data load finishes, sometimes tableView(or scrollView) can not return to its original position(that is, the contentOffset.y is not zero), maybe this problem is from INSPullToRefreshBackgroundView's member externalContentInset's value is not zero(equals to 60.0 when displays not correctly), this problem occurs more frequently when device is iPhone 4S and system version iOS7, can you help to solve this problem? thanks.

**Comment by m1entus** [comment] 2015-07-29 11:04
https://github.com/inspace-io/INSPullToRefresh/issues/51

**Comment by cshl0214** [comment] 2015-07-29 12:26
I have do some test on your solution, set self.automaticallyAdjustsScrollViewInSets = NO and set tableView.contentOffset = CGPoint(0, 0) manually but the problem occured as before. The activityindicator fall down by large distance(about 120pt) and when data load succeeded, the tableView's first row's left top point to navigationBar's bottom is about 60pt, so the interface messed up. 
![ios simulator screen shot 2015 7 29 8 20 38](https://cloud.githubusercontent.com/assets/5669141/8957294/0ceb34ae-3630-11e5-9665-df12cd5132f5.png)

**Comment by m1entus** [comment] 2015-07-29 12:33
Prepare example project and i will help you if i could

**Comment by NBibikov** [comment] 2015-08-05 11:12
I have this issue - http://d.pr/i/10HoN

**Comment by AugustRush** [comment] 2015-08-10 08:57
I had same issue

**Comment by m1entus** [comment] 2015-11-06 08:29
Set self.automaticallyAdjustsScrollViewInsets = NO; this breaks everything

**Comment by m1entus** [comment] 2015-12-03 20:32
Should be fixed in version 1.1.0, if you still will have this bug, please reopen this issue.

**Closed by m1entus** 2015-12-03 20:32 UTC

**Comment by AndyLeeBlue** [comment] 2016-04-01 00:55
I had same issue. And Set self.automaticallyAdjustsScrollViewInsets = NO;Please solve this problem,thanks.

**Comment by m1entus** [comment] 2016-04-01 05:29
I need short example where i can reproduce this bug

**Comment by AndyLeeBlue** [comment] 2016-04-03 05:46
[INSPullToRefreshTest.zip](https://github.com/inspace-io/INSPullToRefresh/files/201187/INSPullToRefreshTest.zip)

**Comment by m1entus** [comment] 2016-04-03 10:39
You must set: `self.tableView.ins_pullToRefreshBackgroundView.shouldResetContentInsetDuringRotation = NO;` , because you have navigationBar translucent and not using storyboard. If you would set `navigationBar.translucent = NO` then you would not have this problem. `shouldResetContentInsetDuringRotation` makes that it automaticully try to set correct inset based on UINavigationBar.

**Comment by AndyLeeBlue** [comment] 2016-04-03 15:23
Thanks. I add shouldResetContentInsetDuringRotation=NO this problem has solved,but still had a small issue,the pull animation is hidden,please look again. thanks again.

**Comment by m1entus** [comment] 2016-04-03 18:50
You you probably didn't import images from project to be able to handle default pull animation
